name: 发布到dist分支

on:
  push:
    branches:
      - master  # 设置触发工作流的源分支名称

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    # Any prerequisite steps
    - uses: actions/checkout@master

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    
    - name: Install MkDocs
      run:
        pip install mkdocs mkdocs-material
    
    - name: Build MkDocs site
      run:
        mkdocs build

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: dist
        FOLDER: ./site
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
